### PR TITLE
Handle missing mandatory output artifacts in workflow execution

### LINKED ISSUE #463: Missing outputs marked as mandatory do not fail the workflow
In the workflow if output artifacts are specified as mandatory then the workflow continues to execute. 

Steps to follow:

1. Create a workflow with an output artefact as mandatory (artefact must not be output by model)
3. Send data to MONAI

**Expected Behaviour**

Workflow Instance marked as failed because mandatory output from Task does not exist. Task should be marked as Failed with a reason and next Task not dispatched

**Actual Behaviour**

Workflow Instance marked as passed and Task as Succeeded

### PR DESCRIPTION
**Pull request by samrooke**
### Description

Mandatory output artefacts were being overlooked during the task execution, allowing the task and workflow to continue. This change checks for missing mandatory output artefacts and updates the task and workflow instance status to failed if they're missing.

Fixes #463 

### Status
Ready

### Types of changes
- [x] Breaking change (fix or new feature that would cause existing functionality to change).
- [x] New tests added to cover the changes.
- [x] All tests passed locally.

### CODE REVIEW

File: src/WorkflowManager/Logging/Logging/Log.cs [hunk 1]
```diff
@@ -161,5 +161,8 @@ public static void LogArtifactPassing(this ILogger logger, Artifact artifact, st
 
         [LoggerMessage(EventId = 35, Level = LogLevel.Debug, Message = "Payload already exists for {payloadId}. This is likley due to being requeued")]
         public static partial void PayloadAlreadyExists(this ILogger logger, string payloadId);
+
+        [LoggerMessage(EventId = 35, Level = LogLevel.Debug, Message = "Mandatory output artefacts for task {taskId} are missing.")]
```
Comment (jackschofield23) [inline src/WorkflowManager/Logging/Logging/Log.cs:165]: update event ID as there are two 35s

**Review by jackschofield23 — APPROVED** [review]

File: src/WorkflowManager/Logging/Logging/Log.cs (hunk 1 above)
Comment (jackschofield23) [reply src/WorkflowManager/Logging/Logging/Log.cs]: Resolved
