### PR TITLE
make dicom checks case insensitive

### LINKED ISSUE #482: Any meta data should not be case sensitive
### Description
When entering a lower case e into the meta data e.g {{ context.dicom.series.all('0008','103e') }} == 'O-MAR, 3 MINUTES'"
Router task was successful but argo task was not
Re-run with the following {{ context.dicom.series.all('0008','103E') }} == 'O-MAR, 3 MINUTES'" and both tasks were successful

### Steps to reproduce
Please share a clear and concise description of the problem.
1. POST router_workflow_3 to workflow manager
2. Trigger a DICOM
3. Check logs and retrieved payload ID
4. In Mongo search for Payload ID in workflow instances
### Expected behavior
Router task & Argo task both to be successful

### Actual behavior
Only router task was successful

### PR DESCRIPTION
**Pull request by jackschofield23**
Signed-off-by: Jack Schofield <jack.schofield@answerdigital.com>

### Description

Fixes #482 .

make dicom checks case insensitive.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [x] All tests passed locally.
- [ ] [Documentation comments](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/documentation-comments) included/updated.

### CODE REVIEW

**Review by samrooke — APPROVED** [review]

File: src/WorkflowManager/Storage/Services/DicomService.cs [hunk 1]
```diff
@@ -87,7 +87,9 @@ public async Task<PatientDetails> GetPayloadPatientDetailsAsync(string payloadId
                     var stream = await _storageService.GetObjectAsync(bucketId, item.FilePath);
                     var jsonStr = Encoding.UTF8.GetString(((MemoryStream)stream).ToArray());
 
-                    var dict = JsonConvert.DeserializeObject<Dictionary<string, DicomValue>>(jsonStr);
+                    var dict = new Dictionary<string, DicomValue>(StringComparer.OrdinalIgnoreCase);
```
Comment (lillie-dae) [inline src/WorkflowManager/Storage/Services/DicomService.cs:90]: would it be worth implementing the sonar suggestion above?

we are only using filePath property on items so you can do...
foreach (var filePath in items.Select(item => item.FilePath)))

Comment (jackschofield23) [reply src/WorkflowManager/Storage/Services/DicomService.cs:90]: Done.
